algoritmo "menu"
// Função : Algoritmo com um menu
// Autor : Delsivan
// Data : 09/11/2021
var
   opcao: inteiro

inicio
      repita
          escreval("Cadastro de Clientes")
          escreval("1 - Incluir")
          escreval("2 - Alterar")
          escreval("3 - Consultar")
          escreval("4 - Excluir")
          escreval("5 - Sair")
          leia(opcao)
      ate opcao = 5
fimalgoritmo
