Algoritmo "Formula 1"

var
          PontosPiloto1, PontosPiloto2, QtdCorridas: inteiro
inicio
      PontosPiloto1 <- 78
      PontosPiloto2 <- 35

      enquanto PontosPiloto2 < PontosPiloto1 faca
         PontosPiloto2 <-  PontosPiloto2 + 12
         QtdCorridas <- QtdCorridas + 1
      fimenquanto
      
      Escreval("Precisa ganhar: ", QtdCorridas, " Corridas para se tornar o Líder do Campeonato.")

fimalgoritmo
