algoritmo "Polegadas para centímetros"
// Função : Converter de polegada para centimetros
// Autor : Delsivan
// Data : 20/11/2021
// Seção de Declarações 
var
   cont, centimetros: inteiro
   polegadas: real

inicio
      para cont de 1 ate 20 passo 1 faca
           centimetros <- cont
           polegadas <- (centimetros*2.54)
           
           Escreval(cont, " = ", polegadas)
      fimpara
      
fimalgoritmo
