algoritmo "Números inteiros"
// Função : Algoritmo que imprima todos os números inteiros de 1 a N ( fornecido pelo usuário).
// Autor :  Delsivan
// Data : 20/11/2021
// Seção de Declarações 
var
   numFinal, cont: inteiro

inicio
      Escreva("Informe o valor final da sequência de numeros: ")
      Leia(numFinal)
      
      para cont de 1 ate numFinal passo 1 faca

           Escreval(cont)

      fimpara
      
fimalgoritmo
